```
     _                                     ____             _       _   ____                                    
    / \   _ __ ___   __ _ _______  _ __   / ___|  ___   ___(_) __ _| | |  _ \ _ __ ___   __ _ _ __ ___  ___ ___ 
   / _ \ | '_ ` _ \ / _` |_  / _ \| '_ \  \___ \ / _ \ / __| |/ _` | | | |_) | '__/ _ \ / _` | '__/ _ \/ __/ __|
  / ___ \| | | | | | (_| |/ / (_) | | | |  ___) | (_) | (__| | (_| | | |  __/| | | (_) | (_| | | |  __/\__ \__ \
 /_/   \_\_| |_| |_|\__,_/___\___/|_| |_| |____/ \___/ \___|_|\__,_|_| |_|   |_|  \___/ \__, |_|  \___||___/___/
                                                                                        |___/                   
```

### Module
__GradientBoostingClassifier__ Gradient Boosting for classification.

### Goal
Investigating the relationship between independent variables or features and a dependent variable or outcome.

### Tools
1. Pandas
2. scikit-learn
3. GradientBoostingClassifier

### Requirement
1. File Definition
2. Data Preparation
3. hotspot_spi.csv generated
 
### Data Source
__${WORKDIR}__/data/ouptut/hotspot_spi.csv

In [1]:
import os
import sys

supervised_dir = os.path.normpath(os.getcwd() + os.sep + os.pardir)
sys.path.append(supervised_dir)
sys.path

['/home/fausto/Development/workspace/amazon-social-progress/ml_models/supervised/classifier',
 '/opt/anaconda3/lib/python39.zip',
 '/opt/anaconda3/lib/python3.9',
 '/opt/anaconda3/lib/python3.9/lib-dynload',
 '',
 '/opt/anaconda3/lib/python3.9/site-packages',
 '/home/fausto/Development/workspace/amazon-social-progress/ml_models/supervised']

In [2]:
import pandas as pd
import numpy as np

import functions_classifier as func
from  load_dataset import LoadDataset, SpiType

from sklearn.ensemble import GradientBoostingClassifier

from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split

## Get the data

In [3]:
load_dataset = LoadDataset()
X, y = load_dataset.return_X_y_clf(spi_type = SpiType.INDICATORS)

columns_names = X.columns

X = scale(X)

In [4]:
print("X.shape:", X.shape, "y.shape:", y.shape)

X.shape: (2313, 49) y.shape: (2313,)


### Split dataset into train and test sets

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=42)

print("X_train.shape:", X_train.shape, "y_train.shape:", y_train.shape)
print("X_test.shape:", X_test.shape, "y_test.shape:", y_test.shape)

X_train.shape: (1619, 49) y_train.shape: (1619,)
X_test.shape: (694, 49) y_test.shape: (694,)


## Modeling

### Building, train and predict model

In [6]:
params =  {
    "learning_rate": 0.1, 
    "max_depth": 4, 
    "min_samples_split": 3, 
    "n_estimators": 360
}

classifier = GradientBoostingClassifier(**params)
classifier.fit(X_train, y_train)
y_predict = classifier.predict(X_test)

### Getting Best Hyperparameter Optimization

*Note: The execution of the code below may take a few minutes or hours.*

*Uncomment and run it when you need to optimize hyperparameters.*

In [7]:
# from sklearn.model_selection import (GridSearchCV)
# import warnings

# warnings.filterwarnings("ignore")

# parameters = {   
#     "n_estimators":[50, 100, 200., 300, 400, 500, 600],
#     "learning_rate": [.1, .5, 1., 1.5, 2., 3.],
#     "algorithm": ("SAMME", "SAMME.R")
# }

# gridsearch = GridSearchCV(AdaBoostClassifier(), parameters)
# gridsearch.fit(X_train, y_train)

# print("Tuned Hyperparameters :", gridsearch.best_params_)
# print("Best Score:",gridsearch.best_score_)

### Predict and show model result

In [8]:
func.show_model_result(classifier, X, y, y_test, y_predict)


Computing cross-validated metrics
----------------------------------------------------------------------
Scores: [0.62203024 0.587473   0.61771058 0.60606061 0.5952381 ]
Mean = 0.61 / Standard Deviation = 0.01

Confunsion Matrix
----------------------------------------------------------------------
[[117  40   8   3]
 [ 30  84  39   7]
 [  7  53  80  38]
 [  2   8  36 142]]

Classification Report
----------------------------------------------------------------------
              precision    recall  f1-score   support

          Q1       0.75      0.70      0.72       168
          Q2       0.45      0.53      0.49       160
          Q3       0.49      0.45      0.47       178
          Q4       0.75      0.76      0.75       188

    accuracy                           0.61       694
   macro avg       0.61      0.61      0.61       694
weighted avg       0.61      0.61      0.61       694

----------------------------------------------------------------------
Accuracy: 0.61
Precici